export const tags = [
  {
    category: 'Content',
    tags: [
      { label: 'Ecchji', value: 9 },
      { label: 'Gore', value: 49 },
      { label: 'Sexual Violence', value: 50 },
      { label: 'Smut', value: 32 },
    ],
  },
  {
    category: 'Format',
    tags: [
      { label: '4-Koma', value: 1 },
      { label: 'Adaptation', value: 42 },
      { label: 'Anthology', value: 43 },
      { label: 'Award Winning', value: 4 },
      { label: 'Anthology', value: 43 },
      { label: 'Doujinshi', value: 7 },
      { label: 'Anthology', value: 43 },
      { label: 'Fan Colored', value: 48 },
      { label: 'Full Color', value: 45 },
      { label: 'Long Strip', value: 36 },
      { label: 'Official Colored', value: 47 },
      { label: 'Oneshot', value: 21 },
      { label: 'User Created', value: 46 },
      { label: 'Web Comic', value: 44 },
    ],
  },
  {
    category: 'Genre',
    tags: [
      { label: 'Action', value: 2 },
      { label: 'Adventure', value: 3 },
      { label: 'Comedy', value: 5 },
      { label: 'Crime', value: 51 },
      { label: 'Drama', value: 8 },
      { label: 'Fantasy', value: 10 },
      { label: 'Historical', value: 13 },
      { label: 'Horror', value: 14 },
      { label: 'Isekai', value: 41 },
      { label: 'Magical Girls', value: 52 },
      { label: 'Mecha', value: 17 },
      { label: 'Medical', value: 18 },
      { label: 'Mystery', value: 20 },
      { label: 'Philosophical', value: 53 },
      { label: 'Psychological', value: 22 },
      { label: 'Romance', value: 23 },
      { label: 'Sci-Fi', value: 25 },
      { label: 'Shoujo Ai', value: 28 },
      { label: 'Shounen Ai', value: 30 },
      { label: 'Slice of Life', value: 31 },
      { label: 'Sports', value: 33 },
      { label: 'Superhero', value: 54 },
      { label: 'Thriller', value: 55 },
      { label: 'Tragedy', value: 35 },
      { label: 'Wuxia', value: 56 },
      { label: 'Yaoi', value: 37 },
      { label: 'Yuri', value: 38 },
    ],
  },
  {
    category: 'Theme',
    tags: [
      { label: 'Aliens', value: 57 },
      { label: 'Animals', value: 58 },
      { label: 'Cooking', value: 6 },
      { label: 'Crossdressing', value: 59 },
      { label: 'Delinquents', value: 61 },
      { label: 'Demons', value: 60 },
      { label: 'Genderswap', value: 62 },
      { label: 'Ghosts', value: 63 },
      { label: 'Gyaru', value: 11 },
      { label: 'Harem', value: 12 },
      { label: 'Incest', value: 83 },
      { label: 'Loli', value: 65 },
      { label: 'Mafia', value: 84 },
      { label: 'Magic', value: 66 },
      { label: 'Martial Arts', value: 16 },
      { label: 'Military', value: 67 },
      { label: 'Monster Girls', value: 64 },
      { label: 'Monsters', value: 68 },
      { label: 'Music', value: 19 },
      { label: 'Ninja', value: 69 },
      { label: 'Office Workers', value: 70 },
      { label: 'Police', value: 71 },
      { label: 'Post-Apocalyptic', value: 72 },
      { label: 'Reincarnation', value: 73 },
      { label: 'Reverse Harem', value: 74 },
      { label: 'Samurai', value: 75 },
      { label: 'School Life', value: 24 },
      { label: 'Shota', value: 76 },
      { label: 'Supernatural', value: 34 },
      { label: 'Survival', value: 77 },
      { label: 'Time Travel', value: 78 },
      { label: 'Traditional Games', value: 80 },
      { label: 'Vampires', value: 79 },
      { label: 'Video Games', value: 40 },
      { label: 'Villainess', value: 85 },
      { label: 'Virtual Reality', value: 81 },
      { label: 'Zombies', value: 82 },
    ],
  },
];

export const demographic = [
  { label: 'Shounen', value: 1 },
  { label: 'Shoujo', value: 2 },
  { label: 'Seinen', value: 3 },
  { label: 'Josei', value: 4 },
];

export const publicationStatus = [
  { label: 'Ongoing', value: 1 },
  { label: 'Completed', value: 2 },
  { label: 'Cancelled', value: 3 },
  { label: 'Hiatus', value: 4 },
];
